# Require seccomp RuntimeDefault or Localhost.
# CIS 5.2.8 (and PSS restricted).
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-seccomp
  annotations:
    policies.kyverno.io/title: Require Seccomp RuntimeDefault
    policies.kyverno.io/category: Pod Security Standards (Restricted)
    policies.kyverno.io/severity: medium
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: seccomp-profile
      match:
        any:
          - resources:
              kinds: [Pod]
      exclude:
        any:
          - resources:
              namespaces: [kube-system, kyverno, kube-bench-scan, local-path-storage, cert-manager]
      validate:
        message: "seccompProfile.type must be RuntimeDefault or Localhost."
        anyPattern:
          - spec:
              securityContext:
                seccompProfile:
                  type: "RuntimeDefault | Localhost"
          - spec:
              containers:
                - securityContext:
                    seccompProfile:
                      type: "RuntimeDefault | Localhost"
