# Disallow pods using the 'default' ServiceAccount.
# CIS 5.1.5.
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-default-sa
  annotations:
    policies.kyverno.io/title: Disallow Default ServiceAccount
    policies.kyverno.io/category: Pod Security Standards (Baseline)
    policies.kyverno.io/severity: medium
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: default-sa
      match:
        any:
          - resources:
              kinds: [Pod]
      exclude:
        any:
          - resources:
              namespaces: [kube-system, kyverno]
      validate:
        message: "Pods must specify a non-default ServiceAccount."
        deny:
          conditions:
            any:
              - key: "{{ request.object.spec.serviceAccountName || 'default' }}"
                operator: Equals
                value: default
